sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_573274d1cd08_key -iv $encrypted_573274d1cd08_iv -in gke-experiment-sa.json.enc -out ../gke-experiment-sa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
