apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: officewhiz-io-tls
spec:
  secretName: officewhiz-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: officewhiz.io
  dnsNames:
    - officewhiz.io
    - www.officewhiz.io